on:
  schedule:
    - cron: "1 16 * * *"

jobs:
  create_issues_action:
    runs-on: ubuntu-latest
    name: create issues action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{secrets.TOKEN}}
